DELETE http://localhost:3001/api/blogs/662d9f838b5147d0cb92fdd0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2MmM2OTQyNDM1MTU5NWMwMDI4MzQ0NCIsImlhdCI6MTcxNDI2NTI1Mn0.fWzjSbEnDuPbUAp8qgNH4SnrFbmXGRmKG3Lw-KU3E2g


